apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: modelserver2-dec18-2
  janus-idp.io/tekton: modelserver2-dec18-2
  backstage.io/kubernetes-id: modelserver2-dec18-2
  backstage.io/kubernetes-namespace: modelserver2-dec18-2 
  app.kubernetes.io/part-of: modelserver2-dec18-2
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- model-config.yaml
